# embed_addon.cmake — bundle an addon directory into a generated C++ header.
#
# Invoked from CMakeLists.txt via `cmake -P` as a custom command. Reads every
# file under SRC_DIR recursively and emits OUT_HEADER containing:
#
#   namespace Addons::Embedded::<AddonName>Files {
#       struct File { const char *path; const unsigned char *data; size_t size; };
#       static const File kFiles[];
#       static constexpr size_t kFileCount;
#   }
#
# Paths are stored relative to SRC_DIR with backslashes (engine-form), so
# the runtime hook can strip `Interface\AddOns\<AddonName>\` from a read
# request and look the suffix up directly.
#
# If `STAMP_VERSION` is non-empty, the TOC file's `## Version:` line is
# rewritten to that value before embedding — lets the build tag flow into
# the embedded addon's metadata. The on-disk TOC stays untouched.
#
# Usage:
#   cmake -DSRC_DIR=... -DOUT_HEADER=... -DADDON_NAME=...
#         [-DSTAMP_VERSION=1.2.3] [-DSTAMP_TOC=MinimapBlips.toc]
#         -P embed_addon.cmake

if(NOT SRC_DIR)
    message(FATAL_ERROR "embed_addon.cmake: SRC_DIR required")
endif()
if(NOT OUT_HEADER)
    message(FATAL_ERROR "embed_addon.cmake: OUT_HEADER required")
endif()
if(NOT ADDON_NAME)
    message(FATAL_ERROR "embed_addon.cmake: ADDON_NAME required")
endif()

file(GLOB_RECURSE INPUT_FILES RELATIVE "${SRC_DIR}" "${SRC_DIR}/*")
list(SORT INPUT_FILES) # deterministic codegen

set(BODY "")
set(MANIFEST "")
set(INDEX 0)
foreach(REL_PATH ${INPUT_FILES})
    set(ABS_PATH "${SRC_DIR}/${REL_PATH}")

    # Optional TOC version stamp — only the addon's TOC file gets touched.
    # We read it as text, rewrite the `## Version:` line, hash that into a
    # temporary buffer in CMake's memory, and feed the modified content to
    # the hex conversion. The on-disk file is never altered.
    set(USE_STAMPED FALSE)
    if(STAMP_VERSION AND STAMP_TOC AND REL_PATH STREQUAL STAMP_TOC)
        file(READ "${ABS_PATH}" TOC_TEXT)
        string(REGEX REPLACE "## Version:[^\n\r]*" "## Version: ${STAMP_VERSION}"
               TOC_TEXT_STAMPED "${TOC_TEXT}")
        # Write to a scratch file so we can re-read as HEX (file(READ ... HEX)
        # is the only way to get raw byte values out of CMake reliably).
        set(SCRATCH "${CMAKE_CURRENT_BINARY_DIR}/_embed_scratch_${INDEX}.bin")
        file(WRITE "${SCRATCH}" "${TOC_TEXT_STAMPED}")
        file(READ "${SCRATCH}" CONTENT_HEX HEX)
        file(REMOVE "${SCRATCH}")
        set(USE_STAMPED TRUE)
    endif()
    if(NOT USE_STAMPED)
        file(READ "${ABS_PATH}" CONTENT_HEX HEX)
    endif()

    string(LENGTH "${CONTENT_HEX}" HEX_LEN)
    math(EXPR FILE_SIZE "${HEX_LEN} / 2")

    # Convert hex string to comma-separated byte literals. 16 bytes per line
    # keeps the generated header readable.
    set(BYTES "")
    set(COL 0)
    set(POS 0)
    while(POS LESS HEX_LEN)
        string(SUBSTRING "${CONTENT_HEX}" ${POS} 2 BYTE)
        if(COL EQUAL 0)
            string(APPEND BYTES "    ")
        endif()
        string(APPEND BYTES "0x${BYTE},")
        math(EXPR POS "${POS} + 2")
        math(EXPR COL "${COL} + 1")
        if(COL EQUAL 16)
            string(APPEND BYTES "\n")
            set(COL 0)
        else()
            string(APPEND BYTES " ")
        endif()
    endwhile()
    if(NOT COL EQUAL 0)
        string(APPEND BYTES "\n")
    endif()

    # Engine stores paths as backslash-separated, original case. The
    # runtime hook compares case-insensitively.
    string(REPLACE "/" "\\\\" REL_PATH_BS "${REL_PATH}")

    string(APPEND BODY "static const unsigned char kData_${INDEX}[] = {\n${BYTES}};\n\n")
    string(APPEND MANIFEST "    { \"${REL_PATH_BS}\", kData_${INDEX}, ${FILE_SIZE} },\n")

    math(EXPR INDEX "${INDEX} + 1")
endforeach()

set(HEADER_CONTENT "// Auto-generated by embed_addon.cmake — do not edit.
// Source: ${SRC_DIR}
// Addon: \"${ADDON_NAME}\"
//
// Embedded as a fallback for users who don't have the addon installed on
// disk. See src/addons/Embedded.cpp for the file-read hook that surfaces
// these buffers to the engine.

#pragma once

#include <cstddef>

namespace Addons::Embedded {

namespace ${ADDON_NAME}Files {

${BODY}static const struct File {
    const char *path;
    const unsigned char *data;
    size_t size;
} kFiles[] = {
${MANIFEST}};

static constexpr size_t kFileCount = sizeof(kFiles) / sizeof(kFiles[0]);

} // namespace ${ADDON_NAME}Files

} // namespace Addons::Embedded
")

file(WRITE "${OUT_HEADER}" "${HEADER_CONTENT}")
message(STATUS "embed_addon: wrote ${OUT_HEADER} (${INDEX} files)")
